using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FarmInterface
{
    internal interface ElementalUnit
    {

        //Common properties of our composite pattern
        //Getters/Setters autogenerated

        string Name { get; set; }
        decimal Price { get; set; }
        int LocationX { get; set; }
        int LocationY { get; set; }
        double Length { get; set; }
        double Width { get; set; }
        double Height { get; set; }

        ElementalUnit Parent { get; set; }


        void Delete(ElementalUnit unit);

    }
}
